// Mocks generated by Mockito 5.4.6 from annotations
// in framescape/test/widget/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:framescape/services/auth_service.dart' as _i3;
import 'package:framescape/services/image_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGenerationResult_0 extends _i1.SmartFake
    implements _i2.GenerationResult {
  _FakeGenerationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i5.User?> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i4.Future<_i5.User?>.value(),
          )
          as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ImageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageService extends _i1.Mock implements _i2.ImageService {
  MockImageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> uploadImage(_i6.File? imageFile, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imageFile, userId]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [imageFile, userId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.GenerationResult> generateFromImage({
    required String? imagePath,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateFromImage, [], {
              #imagePath: imagePath,
              #category: category,
            }),
            returnValue: _i4.Future<_i2.GenerationResult>.value(
              _FakeGenerationResult_0(
                this,
                Invocation.method(#generateFromImage, [], {
                  #imagePath: imagePath,
                  #category: category,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.GenerationResult>);

  @override
  _i4.Stream<List<_i2.GeneratedImage>> getUserImages(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserImages, [userId]),
            returnValue: _i4.Stream<List<_i2.GeneratedImage>>.empty(),
          )
          as _i4.Stream<List<_i2.GeneratedImage>>);
}
